export type CatalogueItem = { name: string; slug: string; brand: string; cats: string[] };

export const catalogue: CatalogueItem[] = [
  { name: "Bhai Bhai Indian Sella Rice 40 Kg", slug: "bhai-bhai-indian-sella-rice-40-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Bhai Bhai Indian Sella Rice 4×10 Kg", slug: "bhai-bhai-indian-sella-rice-4x10-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Bhai Bhai Indian Sella Rice 8×5 Kg", slug: "bhai-bhai-indian-sella-rice-8x5-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Bhai Bhai Pakistani Sella Rice 40 Kg", slug: "bhai-bhai-pakistani-sella-rice-40-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Bhai Bhai Pakistani Sella Rice 4×10 Kg", slug: "bhai-bhai-pakistani-sella-rice-4x10-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Bhai Bhai Pakistani Sella Rice 8×5 Kg", slug: "bhai-bhai-pakistani-sella-rice-8x5-kg", brand: "Bhai Bhai", cats: ["Rice"] },
  { name: "Kaneez Premium Rice 40kg", slug: "kaneez-premium-rice-40kg", brand: "Kaneez", cats: ["Rice"] },
  { name: "Kaneez Premium Rice 4x10kg", slug: "kaneez-premium-rice-4x10kg", brand: "Kaneez", cats: ["Rice"] },
  { name: "Kaneez Premium Rice 8x5kg", slug: "kaneez-premium-rice-8x5kg", brand: "Kaneez", cats: ["Rice"] },
  { name: "Al Azima Cassia Tube (Patta) 20 Kg", slug: "al-azima-cassia-tube-patta-20-kg", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Chana Dal 6×400", slug: "al-azima-chana-dal-6x400", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Chilly Whole Round 1×15 Kg", slug: "al-azima-chilly-whole-round-1x15-kg", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Green Mung 6×400", slug: "al-azima-green-mung-6x400", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Jareesh 6×500", slug: "al-azima-jareesh-6x500", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Masoor Whole 6×400", slug: "al-azima-masoor-whole-6x400", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Red Lentils 6×400", slug: "al-azima-red-lentils-6x400", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Red Masoor Gota 15 Kg", slug: "al-azima-red-masoor-gota-15-kg", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Semolina 6×450", slug: "al-azima-semolina-6x450", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Soya Wadi 20 Kg", slug: "al-azima-soya-wadi-20-kg", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Toor Dal 15 Kg", slug: "al-azima-toor-dal-15-kg", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Toor Dal 6×400", slug: "al-azima-toor-dal-6x400", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Vermicelli 150", slug: "al-azima-vermicelli-150", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Yellow Lentils 6×350", slug: "al-azima-yellow-lentils-6x350", brand: "Al Azima", cats: ["Pulses Legumes & Beans"] },
  { name: "Bhai Bhai Fenugreek Seeds 1×15 Kg", slug: "bhai-bhai-fenugreek-seeds-1x15-kg", brand: "Bhai Bhai", cats: ["Pulses Legumes & Beans"] },
  { name: "Al Azima Black Pepper Powder 6×100", slug: "al-azima-black-pepper-pwdr-6x100", brand: "Al Azima", cats: ["Spices"] },
  { name: "Al Azima Cumin Powder 6×100", slug: "al-azima-cumin-pwdr-6x100", brand: "Al Azima", cats: ["Spices"] },
  { name: "Al Azima Curry Masala 6×200", slug: "al-azima-curry-masala-6x200", brand: "Al Azima", cats: ["Spices"] },
  { name: "Al Azima Red Chilli Powder 6×200", slug: "al-azima-red-chilli-pwdr-6x200", brand: "Al Azima", cats: ["Spices"] },
  { name: "Al Azima Turmeric Powder 6×200", slug: "al-azima-turmeric-pwdr-6x200", brand: "Al Azima", cats: ["Spices"] },
  { name: "Besan Powder Yes Sir 1x15kg", slug: "besan-powder-yes-sir-1x15kg", brand: "Yes Sir", cats: ["Spices"] },
  { name: "Bhai Bhai Corriander Powder 15 Kg", slug: "bhai-bhai-corriander-powder-15-kg", brand: "Bhai Bhai", cats: ["Spices"] },
  { name: "Bhai Bhai Curry Powder 15 Kg", slug: "bhai-bhai-curry-powder-15-kg", brand: "Bhai Bhai", cats: ["Spices"] },
  { name: "Bhai Bhai Red Chilli Powder 15 Kg", slug: "bhai-bhai-red-chilli-powder-15-kg", brand: "Bhai Bhai", cats: ["Spices"] },
  { name: "Bhai Bhai Turmeric Powder 15 Kg", slug: "bhai-bhai-turmeric-powder-15-kg", brand: "Bhai Bhai", cats: ["Spices"] },
  { name: "Al Azima Sugar Coarse 10kg", slug: "al-azima-sugar-coarse-10kg", brand: "Al Azima", cats: ["Sugar"] },
  { name: "Al Azima Sugar Coarse 5kg", slug: "al-azima-sugar-coarse-5kg", brand: "Al Azima", cats: ["Sugar"] },
  { name: "Al Azima Sugar Fine 10kg", slug: "al-azima-sugar-fine-10kg", brand: "Al Azima", cats: ["Sugar"] },
  { name: "Al Azima Sugar Fine 5kg", slug: "al-azima-sugar-fine-5kg", brand: "Al Azima", cats: ["Sugar"] },
  { name: "Al Azima Analogue Milk 48×170", slug: "al-azima-analogue-milk-48x170", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Baked Beans 24×400", slug: "al-azima-baked-beans-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Chick Peas Glass 12×370", slug: "al-azima-chick-peas-glass-12x370", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Chick Peas Glass 12×580", slug: "al-azima-chick-peas-glass-12x580", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Foul Mudammes 24×400", slug: "al-azima-foul-mudammes-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Green Peas 24×400", slug: "al-azima-green-peas-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Kistha Analogue Cream 48×155", slug: "al-azima-kistha-analogue-cream-48x155", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Light Meat Tuna 48×160", slug: "al-azima-light-meat-tuna-48x160", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Light Meat Tuna 48×95", slug: "al-azima-light-meat-tuna-48x95", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Pineapple Slice 24×565", slug: "al-azima-pineapple-slice-24x565", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Red Kidney Beans 24×400", slug: "al-azima-red-kidney-beans-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Sardine In Tomato Sauce 48×200", slug: "al-azima-sardine-in-tomato-sauce-48x200", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Sweet Corn (Dura) 24×340", slug: "al-azima-sweet-corn-dura-24x340", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Tomato Paste 3×4.5 Kg", slug: "al-azima-tomato-paste-3x4-5-kg", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Tomato Paste Easy Open 100×70", slug: "al-azima-tomato-paste-easy-open-100x70", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Tomato Paste Tin 100×70", slug: "al-azima-tomato-paste-tin-100x70", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima Tomato Peeled Mukashar 24×400", slug: "al-azima-tomato-peeled-mukashar-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Al Azima White Beans 24×400", slug: "al-azima-white-beans-24x400", brand: "Al Azima", cats: ["Canned Food"] },
  { name: "Mama’s Choice Yellow Peach Halves 24×425", slug: "mamas-choice-yellow-peach-halves-24x425", brand: "Mama’s Choice", cats: ["Canned Food"] },
  { name: "Royal Palm Tomato Peeled 24×400", slug: "royal-palm-tomato-peeled-24x400", brand: "Royal Palm", cats: ["Canned Food"] },
  { name: "Al Azima Hot Sauce 12×474", slug: "al-azima-hot-sauce-12x474", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Al Azima Hot Sauce 36×88", slug: "al-azima-hot-sauce-36x88", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Al Azima Hot Sauce 4×4.5", slug: "al-azima-hot-sauce-4x4-5", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Al Azima Peanut Butter Creamy 12×227", slug: "al-azima-peanut-butter-creamy-12x227", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Al Azima Peanut Butter Creamy 12×340", slug: "al-azima-peanut-butter-creamy-12x340", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Al Azima Peanut Butter Creamy 12×510", slug: "al-azima-peanut-butter-creamy-12x510", brand: "Al Azima", cats: ["Sauce"] },
  { name: "Mama’s Choice 1000 Island Dressing 12×237", slug: "mamas-choice-1000-island-dressing-12x237", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice French Dressing 12×237", slug: "mamas-choice-french-dressing-12x237", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Ketchup 4×5", slug: "mamas-choice-ketchup-4x5", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Ketchup Squeeze 12×370", slug: "mamas-choice-ketchup-squeeze-12x370", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Mayonnaise 12×325", slug: "mamas-choice-mayonnaise-12x325", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Mayonnaise 12×946", slug: "mamas-choice-mayonnaise-12x946", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Mayonnaise 4×3.78", slug: "mamas-choice-mayonnaise-4x3-78", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Ranch Dressing 12×237", slug: "mamas-choice-ranch-dressing-12x237", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Rose Water 12×450", slug: "mamas-choice-rose-water-12x450", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice White Vinegar 12×473", slug: "mamas-choice-white-vinegar-12x473", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice White Vinegar 4×3.78 Ltr", slug: "mamas-choice-white-vinegar-4x3-78-ltr", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Mama’s Choice Yellow Peach Halves 24×425", slug: "mamas-choice-yellow-peach-halves-24x425-2", brand: "Mama’s Choice", cats: ["Sauce"] },
  { name: "Al Azima Extra Virgin Olive Oil 12×250", slug: "al-azima-extra-virgin-olive-oil-12x250", brand: "Al Azima", cats: ["Oil"] },
  { name: "Al Azima Extra Virgin Olive Oil 12×500", slug: "al-azima-extra-virgin-olive-oil-12x500", brand: "Al Azima", cats: ["Oil"] },
  { name: "Al Azima Shafaf Oil 4×5", slug: "al-azima-shafaf-oil-4x5", brand: "Al Azima", cats: ["Oil"] },
  { name: "Mama’s Choice Oil 4×5", slug: "mamas-choice-oil-4x5", brand: "Mama’s Choice", cats: ["Oil"] },
  { name: "Al Azima Ajino Moto 20×400", slug: "al-azima-ajino-moto-20x400", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Bread Crumbs 6×400", slug: "al-azima-bread-crumbs-6x400", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Crispy Fried Onion 24×400", slug: "al-azima-crispy-fried-onion-24x400", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Crispy Fried Onion 2×4.5 Kg", slug: "al-azima-crispy-fried-onion-2x4-5-kg", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Himalayan Pink Salt 24×500", slug: "al-azima-himalayan-pink-salt-24x500", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Honey (Biyalat ) 48×80", slug: "al-azima-honey-biyalat-48x80", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Honey 12×200", slug: "al-azima-honey-12x200", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Honey 12×400", slug: "al-azima-honey-12x400", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima Milk Powder 6×1.8 Kg", slug: "al-azima-milk-powder-6x1800", brand: "Al Azima", cats: ["Others"] },
  { name: "Al Azima White Oats 24×400", slug: "al-azima-white-oats-24x400", brand: "Al Azima", cats: ["Others"] },
  { name: "Bhai Bhai Puffed Rice (Muri) 10×400", slug: "bhai-bhai-puffed-rice-10x400", brand: "Bhai Bhai", cats: ["Others"] },
  { name: "Bhai Bhai Puffed Rice (Muri) 20×200", slug: "bhai-bhai-puffed-rice-20x200", brand: "Bhai Bhai", cats: ["Others"] },
  { name: "Fresh Basil Seed Drink Cocktail 24×290", slug: "fresh-basil-seed-drink-cocktail-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Lychee 24×290", slug: "fresh-basil-seed-drink-lychee-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Mango 24×290", slug: "fresh-basil-seed-drink-mango-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Passion Fruit 24×290", slug: "fresh-basil-seed-drink-passion-fruit-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Pineapple 24×290", slug: "fresh-basil-seed-drink-pineapple-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Pomegranate 24×29", slug: "fresh-basil-seed-drink-pomegranate-24x290", brand: "Fresh", cats: ["Drinks"] },
  { name: "Fresh Basil Seed Drink Strawberry 24X290", slug: "fresh-basil-seed-drink-strawberry24x290ml", brand: "Fresh", cats: ["Drinks"] },
];

export const catalogueTabs = ["All Products", "Rice", "Pulses Legumes & Beans", "Spices", "Sugar", "Canned Food", "Sauce", "Oil", "Others", "Drinks"] as const;
